import { Sede, Servicio, Promocion, Campania, Paciente, Cita, BlogPost, Especialista } from "./types";

export const ESPECIALISTAS_MOCK: Especialista[] = [
  {
    id: "esp-1",
    name: "Dr. Carlos Mendoza",
    specialty: "Ortodoncia y Estética",
    cop: "COP 14205",
    photo: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=400",
    stars: 4.9,
  },
  {
    id: "esp-2",
    name: "Dra. Sofía Benavides",
    specialty: "Odontopediatría",
    cop: "COP 18412",
    photo: "https://images.unsplash.com/photo-1594824813573-246434de83fb?auto=format&fit=crop&q=80&w=400",
    stars: 5.0,
  },
  {
    id: "esp-3",
    name: "Dr. Luis Tapia",
    specialty: "Implantología y Rehabilitación",
    cop: "COP 11956",
    photo: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=400",
    stars: 4.8,
  },
  {
    id: "esp-4",
    name: "Dra. Natalia Ruiz",
    specialty: "Endodoncia y Odontología General",
    cop: "COP 21087",
    photo: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=400",
    stars: 4.9,
  },
];

export const SEDES_MOCK: Sede[] = [
  {
    id: "sede-sjl-jardines",
    name: "Sede SJL - Jardines Este",
    address: "Jardines Este 524 (frente al parque)",
    distrito: "San Juan de Lurigancho",
    phone: "+51 970 165 171",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m12!1m3!1d3902.327613622432!2d-77.0134015!3d-12.0163353!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c589b2f6efd5%3s0x9105c589b2f6efd5!2sCal.%20Jardines%20Este%20524%2c%20San%20Juan%20de%20Lurigancho!5e0!3m2!1ses!2spe!4v1700000000000",
    googleMapsUrl: "https://maps.google.com/?q=Jardines+Este+524,+San+Juan+de+Lurigancho,+Lima",
    description: "Nuestra clínica principal en SJL con moderna tecnología en rayos X y amplios consultorios familiares para tu comodidad.",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800",
    specialists: [ESPECIALISTAS_MOCK[0], ESPECIALISTAS_MOCK[1], ESPECIALISTAS_MOCK[3]],
  },
  {
    id: "sede-sjl-proceres",
    name: "Sede SJL - Próceres",
    address: "Av. Próceres de la Independencia 2257",
    distrito: "San Juan de Lurigancho",
    phone: "+51 991 555 222",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m12!1m3!1d3902.738914620583!2d-77.0012214!3d-11.9839442!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c59f0f12fa29%3s0x9105c59f0f12fa29!2sAv%20Pr%C3%B3ceres%20de%20la%20Independencia%202257%2c%20San%20Juan%20de%20Lurigancho!5e0!3m2!1ses!2spe!4v1700000000001",
    googleMapsUrl: "https://maps.google.com/?q=Av.+Proceres+de+la+Independencia+2257,+San+Juan+de+Lurigancho,+Lima",
    description: "Estratégicamente ubicada en la avenida principal Próceres de la Independencia, cercana a la estación de metro.",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
    specialists: [ESPECIALISTAS_MOCK[0], ESPECIALISTAS_MOCK[2], ESPECIALISTAS_MOCK[3]],
  },
  {
    id: "sede-miraflores",
    name: "Sede Miraflores",
    address: "Av. Petit Thouars 4350 - Oficina 304",
    distrito: "Miraflores",
    phone: "+51 970 165 171",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1950.4192138243!2d-77.0315513!3d-12.1098315!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c86ea111fa67%3s0x9105c86ea111fa67!2sAv.%20Petit%20Thouars%204350%2c%20Miraflores!5e0!3m2!1ses!2spe!4v1700000000002",
    googleMapsUrl: "https://maps.google.com/?q=Av.+Petit+Thouars+4350,+Miraflores,+Lima",
    description: "Consultorio boutique odontológico de alta estética dental y ortodoncia invisible en pleno corazón de Miraflores.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
    specialists: [ESPECIALISTAS_MOCK[0], ESPECIALISTAS_MOCK[2]],
  },
];

export const SERVICIOS_MOCK: Servicio[] = [
  {
    id: "srv-ortodoncia",
    title: "Ortodoncia (Brackets)",
    shortDesc: "Corrige la alineación de tus dientes con brackets metálicos, cerámicos o autoligantes.",
    fullDesc: "Contamos con tratamientos personalizados de ortodoncia para niños, jóvenes y adultos. Diseñamos un plan de movimiento dental paso a paso para que alcances una oclusión perfecta y una sonrisa estética óptima.",
    detailedPoints: [
      "Brackets metálicos de alta calidad (resistentes y clásicos)",
      "Brackets estéticos (cerámicos y de zafiro que se camuflan con tu esmalte)",
      "Ortodoncia autoligante (menor fricción, movimientos más rápidos)",
      "Estudio de ortodoncia completo: radiografías, modelos y setup digital",
    ],
    duration: "12 a 24 meses",
    priceText: "Evaluación sin costo / Cuotas mensuales cómodas",
    icon: "Tooth",
  },
  {
    id: "srv-odontopediatria",
    title: "Odontopediatría (niños)",
    shortDesc: "Cuidado dental preventivo y amigable para los más pequeños del hogar.",
    fullDesc: "Nuestros odontopediatras logran que la consulta sea divertida y libre de traumas. Nos enfocamos en la prevención de caries, colocación de sellantes, fluorización profesional y orientación del crecimiento de los maxilares.",
    detailedPoints: [
      "Técnicas de manejo de conducta con amor y paciencia",
      "Fluorización en barniz de alta concentración",
      "Sellantes de fosas y fisuras para bloquear caries",
      "Tratamiento de pulpotomías y coronas infantiles si se requiere",
    ],
    duration: "45 min",
    priceText: "Promoción Escolar: 2x100 soles",
    icon: "Baby",
  },
  {
    id: "srv-blanqueamiento",
    title: "Blanqueamiento Dental",
    shortDesc: "Aclara varios tonos en una sola sesión con tecnología LED segura.",
    fullDesc: "Elimina las manchas rebeldes causadas por el café, té o el paso del tiempo. Nuestro blanqueamiento en consultorio es seguro, no daña el esmalte de tus dientes y ofrece resultados drásticos e inmediatos para lucir una sonrisa radiante.",
    detailedPoints: [
      "Sistema de activación por luz fría LED de alta potencia",
      "Gel blanqueador con agentes desensibilizantes integrados",
      "Control estricto por parte del odontólogo especialista",
      "Includes kit de mantenimiento opcional para casa",
    ],
    duration: "1 hora",
    priceText: "Desde S/149 / Consultas Gratuitas",
    icon: "Sparkles",
  },
  {
    id: "srv-limpieza",
    title: "Limpieza Dental Completa",
    shortDesc: "Remoción profunda de sarro y pulido dental para encías sanas.",
    fullDesc: "La profilaxis con ultrasonidos (cavitrón) remueve eficientemente la placa bacteriana dura y manchas superficiales. Finalizamos con pasta abrasiva fina y flúor para devolverle frescura total a tu boca y prevenir la gingivitis.",
    detailedPoints: [
      "Profilaxis ultrasónica indolora de alta precisión",
      "Pulido coronario profesional con pastas profilácticas",
      "Eliminación de manchas con aeropulidor (según caso)",
      "Detección y educación sobre higiene bucal y técnicas de cepillado",
    ],
    duration: "30 min",
    priceText: "Precio Promocional S/50 (Precio regular S/120)",
    icon: "ShieldAlert",
  },
  {
    id: "srv-implantes",
    title: "Implantología Dental",
    shortDesc: "Recupera tus dientes perdidos con implantes estables de titanio.",
    fullDesc: "La solución más moderna y definitiva para reemplazar raíces ausentes. Colocamos el implante y sobre él una corona de porcelana o zirconio idéntica a tus dientes naturales, recuperando tu masticación y autoestima.",
    detailedPoints: [
      "Tornillos de titanio biocompatibles certificados internacionalmente",
      "Planificación digital guiada por tomografía 3D",
      "Cirugía menor altamente confortable y con anestesia local",
      "Rehabilitación con coronas estéticas de máxima resistencia",
    ],
    duration: "2 a 3 sesiones",
    priceText: "Hasta 50% de dcto. (Agenda tu evaluación gratis)",
    icon: "Zap",
  },
  {
    id: "srv-estetica",
    title: "Estética Dental & Carillas",
    shortDesc: "Diseño de sonrisa personalizado con carillas de resina o cerámica.",
    fullDesc: "Modificamos la forma, color, tamaño y posición de tus dientes anteriores con carillas de composite o disilicato de litio de alta gama. Una verdadera transformación estética con mínima o nula preparación dental.",
    detailedPoints: [
      "Carillas de resina fluidas de alta estratificación en una sesión",
      "Carillas de porcelana ultra delgadas de laboratorio dental premium",
      "Análisis fotográfico digital de diseño de sonrisa (DSD)",
      "Cierre de diastemas (espacios) y alineación visual inmediata",
    ],
    duration: "1 a 2 sesiones",
    priceText: "Evaluación estética gratuita",
    icon: "Crown",
  },
  {
    id: "srv-curaciones",
    title: "Curaciones con Resinas",
    shortDesc: "Elimina las caries de manera estética y duradera con resina fotocurable.",
    fullDesc: "Reemplazamos amalgamas oscuras o tratamos caries activas mediante composite estético que imita perfectamente las características ópticas de tus piezas dentales naturales, con un sellado seguro e invisible.",
    detailedPoints: [
      "Remoción cuidadosa del tejido cariado",
      "Resinas estéticas de última generación resistentes al desgaste",
      "Fotocurado con lámpara LED de amplio espectro",
      "Reconstrucción anatómica de cúspides dentales para masticación óptima",
    ],
    duration: "30 min",
    priceText: "Desde S/60 por pieza",
    icon: "Smile",
  },
  {
    id: "srv-endodoncia",
    title: "Tratamiento de Endodoncia",
    shortDesc: "Salva tu diente calmando dolores intensos e infecciones del nervio.",
    fullDesc: "Eliminamos el conducto pulpar infectado para salvar la pieza dental natural. Mediante instrumentación rotatoria mecanizada de vanguardia, logramos tratamientos rápidos, indoloros y altamente exitosos.",
    detailedPoints: [
      "Endodoncia rotatoria mecanizada, óptima y más rápida",
      "Tratamiento inmediato del dolor persistente",
      "Desinfección profunda tridimensional de conductos",
      "Sellado biológico hermético posterior",
    ],
    duration: "1 a 2 sesiones",
    priceText: "Desde S/180 / Diagnóstico incluido",
    icon: "HeartPulse",
  },
];

export const PROMOCIONES_MOCK: Promocion[] = [
  {
    id: "promo-limpieza-50",
    title: "Limpieza Dental Completa",
    description: "Incluye remoción de sarro con ultrasonido, pulido, profilaxis profesional completo y diagnóstico digital odontológico.",
    code: "LIMPIEZA50",
    oldPrice: 120,
    newPrice: 50,
    cuposDisponibles: 12,
    totalCupos: 50,
    fechaVencimiento: "2026-06-30",
    isActive: true,
  },
  {
    id: "promo-escolar-100",
    title: "Promoción Escolar 2x100 Soles",
    description: "¡Atención mamás! Trae a dos niños (o a un hermano y tú) por solo S/100. Incluye: Evaluación + Profilaxis + Aplicación de Flúor en Barniz.",
    code: "ESCOLAR2X100",
    oldPrice: 240,
    newPrice: 100,
    cuposDisponibles: 8,
    totalCupos: 30,
    fechaVencimiento: "2026-07-15",
    isActive: true,
    isSchoolPromo: true,
  },
  {
    id: "promo-campana-evaluacion",
    title: "Campaña: Consulta y Diagnóstico Gratis",
    description: "Aprovecha consultas gratuitas en todas nuestras especialidades (Brackets, Implantes, Coronas). Incluye toma de fotos intraorales digitales.",
    code: "CONSULTASGRATIS",
    oldPrice: 60,
    newPrice: 0,
    cuposDisponibles: 25,
    totalCupos: 150,
    fechaVencimiento: "2026-06-25",
    isActive: true,
  },
  {
    id: "promo-ortodoncia-dcto",
    title: "Hasta 50% de Descuento en Especialidades",
    description: "Descuentos increíbles de hasta 50% en cuota inicial de ortodoncia, carillas dentales por bloque, y cirugías de implantes.",
    code: "ESPECIALIDAD50",
    oldPrice: 200,
    newPrice: 100,
    cuposDisponibles: 18,
    totalCupos: 40,
    fechaVencimiento: "2026-06-28",
    isActive: true,
  },
];

export const CAMPANIAS_MOCK: Campania[] = [
  {
    id: "camp-junio",
    title: "Campaña de Profilaxis y Diagnóstico Familiar",
    subtitle: "Evalúate a ti y a tus seres queridos sin costo este fin de semana",
    dateStr: "Sábado 20 y Domingo 21 de Junio, 2026",
    durationHours: "9:00 AM a 6:00 PM",
    location: "Sedes SJL (Jardines & Próceres) y Miraflores",
    description: "Una iniciativa comunitaria de Mundo Dental para incentivar la prevención médica de caries y gingivitis. Atendido por todos nuestros especialistas.",
    benefits: [
      "Consulta con cámara intraoral digital totalmente gratis.",
      "Regalo sorpresa para la higiene oral de los niños.",
      "Descuento sorpresa del 10% adicional si agendan curación ese día.",
    ],
    gifts: ["Cepillo Ortodóntico / Infantil Colgate", "Crema dental en miniatura", "Guía de cepillado"],
    isActive: true,
  },
];

export const BLOG_MOCK: BlogPost[] = [
  {
    id: "blog-1",
    title: "¿Cómo cuidar tus brackets y evitar caries?",
    summary: "Si acabas de iniciar tu tratamiento de ortodoncia, el cepillado correcto cambia. Te enseñamos los pasos clave.",
    category: "Ortodoncia",
    author: "Dr. Carlos Mendoza",
    date: "10 de Junio, 2026",
    readTime: "4 min de lectura",
    image: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&q=80&w=600",
    content: "Llevar brackets es el primer paso para lucir una sonrisa de película. Sin embargo, los brackets metálicos o estéticos facilitan que los restos de comida queden retenidos, lo que puede provocar placa, inflamación de encías (gingivitis) y, a largo plazo, marcas blancas o caries alrededor del alambre dental.\n\nPara evitar esto, debes optimizar tu limpieza diaria:\n1. **Usa un cepillo de dientes específico**: Los cepillos de ortodoncia tienen cerdas en forma de 'V' para limpiar entre los brackets y los dientes al mismo tiempo.\n2. **Complementa con cepillos interproximales**: Son pequeños cepillitos cilíndricos que se meten debajo del arco para sacar comida rebelde.\n3. **Usa hilo dental enhebrado o irrigador**: El hilo dental no pasa directo; usa enhebradores especiales para deslizarlo por debajo de los brackets.\n4. **Reduce carbohidratos pegajosos**: Evita gomitas, chicles, turrones, manzanas a mordiscos u otros alimentos compactos que doblen el arco.\n\nSiguiendo estos pasos básicos y acudiendo a tu profilaxis cada 4-6 meses mantendrás un esmalte reluciente y saludable.",
  },
  {
    id: "blog-2",
    title: "La importancia de la limpieza dental con ultrasonido profesional",
    summary: "Muchas personas confunden el cepillado diario con una profilaxis clínica profesional. Conoce las marcadas diferencias.",
    category: "General",
    author: "Dra. Natalia Ruiz",
    date: "05 de Junio, 2026",
    readTime: "3 min de lectura",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=600",
    content: "La acumulación de sales minerales en la placa bacteriana de los dientes crea el llamado 'sarro' dental (cálculo), un bloque de consistencia pétrea de color amarillento que se adhiere fuertemente cerca de la encía.\n\nPor mucho que te cepilles con fuerza en casa, el cepillo de cerdas normales no puede desprender el sarro duro. Solo una limpieza dental asistida con ultrasonidos clínico consigue:\n- Vibrar micrométricamente para romper los bloques de sarro sin desgastar tu esmalte.\n- Limpiar las bolsas periodontales que causan mal aliento (halitosis) y retracción de encías.\n- Retirar manchas de té, café y tabaco superficiales de forma segura.\n\nSe aconseja realizar este procedimiento cada 6 meses. ¡Aprovecha que en Mundo Dental tenemos el procedimiento de profilaxis ultrasónica profunda en oferta especial por solo S/50 soles!",
  },
  {
    id: "blog-3",
    title: "Primera visita al dentista: ¿Cuándo llevar a los niños?",
    summary: "No esperes a que tu pequeño tenga dolor de muelas para programar su cita. El aprendizaje amigable desde temprano previene miedos crónicos.",
    category: "Odontopediatría",
    author: "Dra. Sofía Benavides",
    date: "28 de Mayo, 2026",
    readTime: "5 min de lectura",
    image: "https://images.unsplash.com/photo-1484665754804-74b091211472?auto=format&fit=crop&q=80&w=600",
    content: "La Sociedad Peruana de Odontopediatría aconseja realizar la primera evaluación del bebé cerca del primer año de vida, momento en el que brotan los primeros 'dientes de leche'.\n\n¿Por qué es importante esta consulta tan temprana?\n- **Prevención de la caries de biberón**: Muchas mamás endulzan las bebidas nocturnas, lo que desgasta violentamente el esmalte fino infantil.\n- **Evaluación del frenillo lingual**: Detectamos dificultades para la lactancia o la correcta pronunciación.\n- **Hábitos de succionar el dedo**: Un hábito prolongado de chuparse el dedo o uso excesivo de chupón deforma el paladar y genera mordidas abiertas.\n\nEn Mundo Dental contamos con consultorios especialmente ambientados para infantes con dinámicas de juegos y premios lúdicos para alejar por completo el miedo al dentista.",
  },
];

export const PACIENTES_MOCK: Paciente[] = [
  {
    id: "pac-1",
    name: "María Elena Quispe",
    phone: "983452109",
    dni: "45293021",
    age: 34,
    email: "maria.quispe@gmail.com",
    locationPreference: "sede-sjl-jardines",
    recordNumber: "HC-2026-6401",
    notes: "Paciente con alta sensibilidad dental. Recibiendo ortodoncia metálica activa desde marzo 2025.",
    registrationDate: "2025-03-12",
    treatmentsHistory: [
      {
        date: "2026-05-15",
        treatment: "Control Mensual de Ortodoncia",
        specialistName: "Dr. Carlos Mendoza",
        notes: "Cambio de arcos superiores e inferiores Niti 16x22. Colocación de ligaduras celestes.",
        cost: 120,
      },
      {
        date: "2026-04-10",
        treatment: "Curación con Resina Simple",
        specialistName: "Dra. Natalia Ruiz",
        notes: "Curación de caries profunda oclusal en pieza 46. Sin sensibilidad post operatoria.",
        cost: 70,
      },
      {
        date: "2025-03-12",
        treatment: "Instalación de Brackets Metálicos",
        specialistName: "Dr. Carlos Mendoza",
        notes: "Se instala aparatología completa Roth de pre-ortodoncia. Paciente toleró excelente tratamiento.",
        cost: 800,
      },
    ],
  },
  {
    id: "pac-2",
    name: "Juan Carlos Flores Ramos",
    phone: "972115584",
    dni: "09843217",
    age: 45,
    email: "jflores@outlook.com",
    locationPreference: "sede-miraflores",
    recordNumber: "HC-2026-3199",
    notes: "Tiene prótesis removible superior antigua. Interesado hoy en Implante Unidad Monolítica.",
    registrationDate: "2025-08-20",
    treatmentsHistory: [
      {
        date: "2026-03-10",
        treatment: "Evaluación Quirúrgica Implante",
        specialistName: "Dr. Luis Tapia",
        notes: "Evaluación de tomografía 3D ósea. Hueso alveolar en óptimas dimensiones para implante dental en pieza 11.",
        cost: 0,
      },
      {
        date: "2025-08-20",
        treatment: "Profilaxis Ultrasonido Dental profunda",
        specialistName: "Dra. Natalia Ruiz",
        notes: "Ultrasonido cavitrón completo de cuadrantes 1 a 4. Pulido e instrucción de higiene oral.",
        cost: 50,
      },
    ],
  },
  {
    id: "pac-3",
    name: "Ana Sofía Benítez",
    phone: "914598001",
    dni: "71223405",
    age: 8,
    email: "carla.benitez_mama@gmail.com",
    locationPreference: "sede-sjl-proceres",
    recordNumber: "HC-2026-1025",
    notes: "Asiste con su mamá (Carla Benítez). Muy traviesa, le encanta el Dr. Sofía por sus obsequios de globología.",
    registrationDate: "2026-01-10",
    treatmentsHistory: [
      {
        date: "2026-05-20",
        treatment: "Aplicación de Flúor Profesional y Limpieza",
        specialistName: "Dra. Sofía Benavides",
        notes: "Profilaxis infantil adaptada y flúor barniz 5% sabor frutilla. Excelente cuidado preventivo.",
        cost: 50,
      },
      {
        date: "2026-01-10",
        treatment: "Sellantes Autocurables",
        specialistName: "Dra. Sofía Benavides",
        notes: "Sellado de fosas oclusales profundas sanas en molares 16, 26, 36, 46 para blindaje caries.",
        cost: 160,
      },
    ],
  },
  {
    id: "pac-4",
    name: "Luis Alberto Tapia Alva",
    phone: "951478201",
    dni: "43210987",
    age: 29,
    email: "luis.tapia@gmail.com",
    locationPreference: "sede-sjl-jardines",
    recordNumber: "HC-2026-5544",
    notes: "Sufre de bruxismo nocturno. Utiliza férula miorrelajante rígida de acrílico.",
    registrationDate: "2026-02-15",
    treatmentsHistory: [
      {
        date: "2026-04-02",
        treatment: "Control y Entrega de Placa de Bruximo",
        specialistName: "Dr. Carlos Mendoza",
        notes: "Placa excelente estabilidad y desoclusión posterior libre. Control en 3 meses.",
        cost: 350,
      },
    ],
  },
];

export const CITAS_MOCK: Cita[] = [
  {
    id: "cit-1",
    patientName: "María Elena Quispe",
    patientPhone: "983452109",
    patientDni: "45293021",
    sedeId: "sede-sjl-jardines",
    serviceId: "srv-ortodoncia",
    specialistId: "esp-1",
    date: "2026-06-16",
    time: "15:00",
    status: "confirmada",
    notes: "Ajuste mensual de brackets.",
    cost: 120,
    createdAt: "2026-06-10T14:20:00",
  },
  {
    id: "cit-2",
    patientName: "Luis Alberto Tapia Alva",
    patientPhone: "951478201",
    patientDni: "43210987",
    sedeId: "sede-sjl-jardines",
    serviceId: "srv-limpieza",
    specialistId: "esp-4",
    date: "2026-06-16",
    time: "16:15",
    status: "pendiente",
    notes: "Viene por la promoción de profilaxis S/50.",
    cost: 50,
    promoApplied: "promo-limpieza-50",
    createdAt: "2026-06-12T09:10:00",
  },
  {
    id: "cit-3",
    patientName: "Ana Sofía Benítez",
    patientPhone: "914598001",
    patientDni: "71223405",
    sedeId: "sede-sjl-proceres",
    serviceId: "srv-odontopediatria",
    specialistId: "esp-2",
    date: "2026-06-17",
    time: "10:30",
    status: "confirmada",
    notes: "Promoción escolar dual infantil preventivo.",
    cost: 100,
    promoApplied: "promo-escolar-100",
    createdAt: "2026-06-11T12:44:00",
  },
  {
    id: "cit-4",
    patientName: "Juan Carlos Flores Ramos",
    patientPhone: "972115584",
    patientDni: "09843217",
    sedeId: "sede-miraflores",
    serviceId: "srv-implantes",
    specialistId: "esp-3",
    date: "2026-06-18",
    time: "11:00",
    status: "pendiente",
    notes: "Evaluación detallada gratuita para planificar corona zirconio en implante.",
    cost: 0,
    promoApplied: "promo-campana-evaluacion",
    createdAt: "2026-06-14T08:33:00",
  },
  {
    id: "cit-5",
    patientName: "Gino Renato Alcantara",
    patientPhone: "981223344",
    patientDni: "40201088",
    sedeId: "sede-miraflores",
    serviceId: "srv-blanqueamiento",
    specialistId: "esp-1",
    date: "2026-06-19",
    time: "17:00",
    status: "atendida",
    notes: "Blanqueamiento Express luces LED.",
    cost: 149,
    createdAt: "2026-06-10T10:00:00",
  },
  {
    id: "cit-6",
    patientName: "Claudia Patricia Rojas",
    patientPhone: "991443322",
    patientDni: "48201201",
    sedeId: "sede-sjl-proceres",
    serviceId: "srv-limpieza",
    specialistId: "esp-4",
    date: "2026-06-20",
    time: "09:30",
    status: "pendiente",
    notes: "Primera profilaxis profiláctica de sarro.",
    cost: 50,
    promoApplied: "promo-limpieza-50",
    createdAt: "2026-06-15T15:20:00",
  },
  {
    id: "cit-7",
    patientName: "Junior David Salas",
    patientPhone: "931221144",
    patientDni: "43201402",
    sedeId: "sede-sjl-jardines",
    serviceId: "srv-estetica",
    specialistId: "esp-1",
    date: "2026-06-21",
    time: "14:00",
    status: "pendiente",
    notes: "Diseño de sonrisa de resinas.",
    cost: 400,
    createdAt: "2026-06-15T17:10:00",
  }
];
